# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mark Dunne
description:      'Computer Science student at University College Cork'
url:              http://markdunne.github.io
baseurl:          /

author:
  name:           'Mark Dunne'
  url:            http://markdunne.github.io

# Custom vars
version:          1.0.0
