# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mark Dunne
tagline:          'A Jekyll theme'
description:      'Computer Science student at University College Cork'
url:              http://markdunne.github.io
baseurl:          /

author:
  name:           'Mark Dunne'
  url:            http://markdunne.github.io

paginate:         6

# Custom vars
version:          1.0.0
